#!/bin/bash

D2J=/Users/adamvh/Documents/Programming/dta_tool/working_copy/dta2json

for f in $*
do
	echo $D2J $f ${f%.*}-hit.txt ${f%.*}-time.txt ${f%.*}-wave.txt
	$D2J $f ${f%.*}-hit.txt ${f%.*}-time.txt ${f%.*}-wave.txt &
done