#!/bin/bash

D2J=/Users/adamvh/Documents/Programming/dta_tool/working_copy/dta2json

for f in $*
do
	echo $D2J $f /dev/null /dev/null ${f%.*}-wave.json
	$D2J $f /dev/null /dev/null ${f%.*}-wave.json &
done