#!/bin/bash

D2J=/Users/adamvh/Documents/Programming/dta_tool/working_copy/dta2json

for f in $*
do
	echo $D2J $f ${f%.*}-hit.json ${f%.*}-time.json /dev/null
	time $D2J $f ${f%.*}-hit.json ${f%.*}-time.json /dev/null > ${f%.*}.log &
done